apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: lba3uktc4-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:62e2d3d84e7bb410dd797ef5f2b872a45674a7ab@sha256:620041fe5cc9b8bf92ad04d8a5b5e0f61d68945676d61da5aa0030e7b3ffc259
        name: container-image  
